name: email-api

spring:
  data:
    mongodb:
      auto-index-creation: true
      database: email-api
      authentication-database: email-api
  jackson:
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
