name: email-api

email:
  api:
    time-offset: "+2"

spring:
  data:
    mongodb:
      auto-index-creation: true
      database: emails
      authentication-database: emails
  jackson:
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
logging:
  level:
    org.springframework.web.servlet.mvc.support: WARN
    org.springframework: INFO
    root: INFO

