name: email-sender

email:
  api:
    time-offset: "+2"

spring:
  rabbitmq:
    host: 127.0.0.1
    podr: 5672
    username: guest
    password: guest
  data:
    mongodb:
      auto-index-creation: true
      database: emails
      authentication-database: emails
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  jackson:
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
logging:
  level:
    org.springframework.web.servlet.mvc.support: WARN
    org.springframework: INFO
    root: INFO

